
notifications: 
    email:
      on_success: never
      on_failure: never

language: php
php:
    - 5.6
    - 5.5
    - hhvm
    
before_script:
    #- wget https://scrutinizer-ci.com/ocular.phar
    #- composer install

script: 
    - phpunit --bootstrap test/config.php test